### ISSUE TITLE
모바일 반응형 작업

### ISSUE THREAD

**Issue by lecto17** [JobCatcher/recommend-lunch-menu#7]
## Todo
- [x] 모바일 반응형 작업
- [x] 맛집 클릭 시 지도에 하이라이트 
- [x] 클릭한 맛집 현재 지점에서 거리 표시해주기
- [x] 액티브된 상태에서 클릭 시 해당 맛집을 네이버로 검색
- [x] 같은 마커 연속적으로 클릭 안되는 버그 픽스
- [x] 마커 클릭하여 네이버 검색 시 dongName 검색
