### ISSUE TITLE
현재 위치 기반 주변 맛집 정보 가져오는 API 연동

### ISSUE THREAD

**Issue by lecto17** [JobCatcher/recommend-lunch-menu#8]
## Todo
- [x] 현재 위치 기반 주변 맛집 정보 가져오는 API 연동
  - https://team-json-delivery.github.io/posts/system-design-interview-proximity-service/
- [x] 맛집 목록 마커로 표시
- [ ] 현재 위치 기반으로 맛집 거리 측정
- 맛집 컴포넌트 layout
  - [x] overlay로 띄우기
  - [x] 리스트 형태로 띄우기
  - [ ] 합성 컴포넌트로 구성
- [x] 지도 혹은 테이블에서 맛집 클릭 시 하이라이트 표시 -> 지도, 리스트에서 식당 클릭 시 naver로 검색되도록 작업
